import type { OrganizationLivePreviewRole } from "@/lib/organizations/preview-client";

export const NOTIFICATION_TYPES = [
  "practice_assigned",
  "teacher_feedback",
  "assignment_completed",
  "organization_request",
  "organization_invitation",
] as const;

export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
export type NotificationRequestKind = "join" | "leave" | "history_access_change";

export interface NotificationActor {
  displayName: string | null;
  username: string | null;
}

export interface NotificationOrganization {
  id: string;
  name: string;
}

export interface NotificationAssignment {
  id: string;
  title: string;
  practiceKind: string | null;
  practiceId: string | null;
  dueAt: string | null;
}

export interface AccountNotification {
  id: string;
  type: NotificationType;
  createdAt: string;
  readAt: string | null;
  actor: NotificationActor | null;
  organization: NotificationOrganization | null;
  assignment: NotificationAssignment | null;
  requestKind: NotificationRequestKind | null;
  /** Same-origin route generated by BandUp. Absolute URLs are rejected client-side. */
  actionPath: string | null;
}

export interface NotificationPageResponse {
  notifications: AccountNotification[];
  unreadCount: number;
  nextCursor: string | null;
}

export interface NotificationMutationResponse {
  ok: true;
  unreadCount: number;
}

export interface NotificationCopy {
  title: string;
  body: string;
  /** Short verb shown on the destination link. */
  actionLabel: string;
  /** Explains why the destination deserves the recipient's attention. */
  attentionLabel: string;
}

export interface NotificationRequestOptions {
  previewRole?: OrganizationLivePreviewRole | null;
  signal?: AbortSignal;
  cursor?: string | null;
}

export const NOTIFICATIONS_CHANGED_EVENT = "bandup:notifications-changed";
