/*
  Practice writing autosaves, and throws the draft away the moment it stops
  being a rescue.

  What this file exists to prevent is the state the page shipped in until now:
  the essay lived in React state and nowhere else, so a pull-to-refresh, a phone
  locking or a background tab the browser reclaimed took twenty minutes of
  somebody's evening with it and left nothing to go back to. The first test
  below is the one that would have failed on that page — an essay written, the
  screen coming back, and the words being there.

  The harder half is the other direction, and it is where a careless fix does
  more damage than the missing feature did. Clearing on unmount is the obvious
  implementation and it is wrong twice: a reload is not a departure, and neither
  is StrictMode's development remount, and a draft cleared by either of those is
  a guard that deletes exactly the work it was added to save. So the page tells
  a deliberate exit from an accident by reading the address bar, the same way
  app/exam/page.tsx does for the mock sitting, and the shape of that check is
  asserted here rather than left to be rediscovered.
*/
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { register } from "node:module";
import { join } from "node:path";
import { test } from "node:test";
import { pathToFileURL } from "node:url";

register("./alias-resolve.mjs", import.meta.url);

const root = process.cwd();
const src = (...parts) => readFileSync(join(root, ...parts), "utf8");
const load = (...parts) => import(pathToFileURL(join(root, ...parts)).href);

const DRAFT_KEY = "bandup.writing-draft.v1";
const TASK_1 = "writing-1";
const TASK_2 = "writing-2";

const durable = new Map();
const perTab = new Map();

const shelf = (map) => ({
  getItem: (key) => (map.has(key) ? map.get(key) : null),
  setItem: (key, value) => map.set(key, String(value)),
  removeItem: (key) => map.delete(key),
  clear: () => map.clear(),
});

const refuses = () => {
  throw new Error("storage disabled");
};

const blocked = {
  getItem: refuses,
  setItem: refuses,
  removeItem: refuses,
  clear: refuses,
};

globalThis.window = {
  localStorage: shelf(durable),
  sessionStorage: shelf(perTab),
  dispatchEvent: () => true,
  addEventListener: () => {},
  removeEventListener: () => {},
};
globalThis.StorageEvent = class StorageEvent extends Event {
  constructor(type, init = {}) {
    super(type);
    this.key = init.key ?? null;
  }
};

const {
  AUTOSAVE_DELAY_MS,
  DRAFT_LIFETIME_MS,
  discardWritingDraft,
  discardWritingDrafts,
  loadWritingDraft,
  saveWritingDraft,
} = await load("lib", "writing-draft.ts");
const { clearProgressStore } = await load("lib", "progress", "storage.ts");

function freshTab() {
  perTab.clear();
  durable.clear();
  globalThis.window.sessionStorage = shelf(perTab);
  globalThis.window.localStorage = shelf(durable);
}

// ---------------------------------------------------------------------------
// The rescue itself
// ---------------------------------------------------------------------------

test("an essay typed and then lost to a reload comes back", () => {
  freshTab();
  const essay = "Some countries invest heavily in high-speed rail, while others";

  saveWritingDraft(TASK_1, essay);

  // A reload is a fresh module in a fresh page against the same sessionStorage,
  // which is what reading it straight back out models.
  assert.equal(loadWritingDraft(TASK_1), essay);
});

test("each task keeps its own draft, so switching between them costs nothing", () => {
  freshTab();

  saveWritingDraft(TASK_1, "The chart shows electricity generated by source.");
  saveWritingDraft(TASK_2, "It is sometimes argued that museums should be free.");

  assert.equal(loadWritingDraft(TASK_1), "The chart shows electricity generated by source.");
  assert.equal(loadWritingDraft(TASK_2), "It is sometimes argued that museums should be free.");

  // One key, one map — a key per task would leave a sign-out and a clear
  // sweeping storage by prefix to be sure they had taken them all.
  assert.deepEqual([...perTab.keys()].filter((key) => key.startsWith("bandup.writing-draft")), [
    DRAFT_KEY,
  ]);
});

test("a box emptied on purpose leaves nothing behind to restore", () => {
  freshTab();

  saveWritingDraft(TASK_1, "A false start.");
  saveWritingDraft(TASK_1, "");

  assert.equal(loadWritingDraft(TASK_1), "");
  assert.equal(perTab.has(DRAFT_KEY), false, "an empty draft store should not be a stored key");

  // Whitespace is not an essay either, and a page merely opened must not write.
  saveWritingDraft(TASK_1, "   \n  ");
  assert.equal(perTab.has(DRAFT_KEY), false);
});

// ---------------------------------------------------------------------------
// When it stops being a rescue
// ---------------------------------------------------------------------------

test("a stale draft is not restored over a task the learner has moved on from", () => {
  freshTab();
  const written = Date.parse("2026-08-31T21:00:00.000Z");

  saveWritingDraft(TASK_1, "Written last night.", written);

  assert.equal(
    loadWritingDraft(TASK_1, written + DRAFT_LIFETIME_MS - 60_000),
    "Written last night.",
    "a phone locked overnight and picked up at breakfast is what the window is for",
  );
  assert.equal(
    loadWritingDraft(TASK_1, written + DRAFT_LIFETIME_MS),
    "",
    "beyond the window a restore is a surprise rather than a rescue",
  );
});

test("a clock that jumped backwards does not delete work that is minutes old", () => {
  freshTab();
  const written = Date.parse("2026-08-31T21:00:00.000Z");

  saveWritingDraft(TASK_1, "Typed a moment ago.", written);

  assert.equal(
    loadWritingDraft(TASK_1, written - 60 * 60 * 1000),
    "Typed a moment ago.",
    "between two ways of being wrong, the one that does not delete an essay",
  );
});

test("submitting forgets that task's draft and leaves the other task's alone", () => {
  freshTab();
  saveWritingDraft(TASK_1, "Marked and recorded.");
  saveWritingDraft(TASK_2, "Still being written.");

  discardWritingDraft(TASK_1);

  assert.equal(loadWritingDraft(TASK_1), "");
  assert.equal(loadWritingDraft(TASK_2), "Still being written.");
});

test("leaving the writing paper forgets both tasks, not just the one on screen", () => {
  freshTab();
  saveWritingDraft(TASK_1, "Task one.");
  saveWritingDraft(TASK_2, "Task two.");

  discardWritingDrafts();

  assert.equal(loadWritingDraft(TASK_1), "");
  assert.equal(loadWritingDraft(TASK_2), "");
  assert.equal(perTab.has(DRAFT_KEY), false);
});

test("signing out takes any half-written essay with the rest of the learner's work", () => {
  freshTab();
  saveWritingDraft(TASK_1, "Unfinished, and not the next person's to read.");

  clearProgressStore();

  assert.equal(perTab.has(DRAFT_KEY), false);
});

// ---------------------------------------------------------------------------
// Storage that will not cooperate
// ---------------------------------------------------------------------------

test("a browser that refuses storage costs the guard, never the page", () => {
  freshTab();
  globalThis.window.sessionStorage = blocked;
  globalThis.window.localStorage = blocked;

  // Every one of these is called from render or from an event handler on a page
  // whose live copy of the essay is in React state. A throw here would take the
  // essay down with it, which is the opposite of the point.
  assert.doesNotThrow(() => saveWritingDraft(TASK_1, "Private window."));
  assert.doesNotThrow(() => discardWritingDraft(TASK_1));
  assert.doesNotThrow(() => discardWritingDrafts());
  assert.equal(loadWritingDraft(TASK_1), "");

  freshTab();
});

test("a corrupted or out-of-date store reads as nothing rather than throwing", () => {
  freshTab();

  perTab.set(DRAFT_KEY, "{ not json");
  assert.equal(loadWritingDraft(TASK_1), "");

  perTab.set(DRAFT_KEY, JSON.stringify({ version: 0, drafts: { [TASK_1]: "an older shape" } }));
  assert.equal(loadWritingDraft(TASK_1), "");

  perTab.set(DRAFT_KEY, JSON.stringify({ version: 1, drafts: { [TASK_1]: { text: 12 } } }));
  assert.equal(loadWritingDraft(TASK_1), "");
});

// ---------------------------------------------------------------------------
// How the page uses it
// ---------------------------------------------------------------------------

/* Comments explain the traps; they must not be what satisfies the tests. */
const code = (text) => text.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/[^\n]*/g, "");
const page = () => code(src("app", "practice", "writing", "page.tsx"));

test("the essay is restored into the first render, not pushed in a frame later", () => {
  const body = page();

  assert.match(
    body,
    /useState\(\(\) => loadWritingDraft\(/,
    "restoring in an effect paints an empty box over the essay somebody is relieved to see",
  );
});

test("the autosave is debounced rather than run on every keystroke", () => {
  const body = page();

  assert.match(body, /setTimeout\(\(\) => saveWritingDraft\([^)]*\), AUTOSAVE_DELAY_MS\)/);
  assert.match(body, /return \(\) => clearTimeout\(timer\)/);
  assert.ok(
    AUTOSAVE_DELAY_MS > 0 && AUTOSAVE_DELAY_MS <= 1000,
    "long enough to be one write per pause, short enough that an accident takes a word",
  );
});

test("submitting clears the draft, and a failed submit deliberately does not", () => {
  const body = page();

  const submit = body.slice(body.indexOf("async function submit"), body.indexOf("const resetTask"));
  const cleared = submit.indexOf("discardWritingDraft(task.id)");
  assert.ok(cleared > 0, "a marked essay leaves a draft waiting to reappear under a finished task");
  assert.ok(
    cleared < submit.indexOf("} catch"),
    "the clear belongs on the success path — a failed submit is when the draft is worth most",
  );
});

test("a departure clears the draft and a reload cannot, because the check is the address bar", () => {
  const body = page();

  const cleanups = [...body.matchAll(/discardWritingDrafts\(\)/g)];
  assert.equal(cleanups.length, 1, "one departure, one place that acts on it");

  /*
    The whole feature is in this shape. An effect cleanup is what a navigation
    inside the app runs and a reload never does; the pathname check is what
    stops StrictMode's development remount — and a task switch, and the chooser,
    both of which stay on /practice/writing — from reading as a departure.
  */
  assert.match(
    body,
    /useEffect\(\s*\(\)\s*=>\s*\{\s*return\s*\(\)\s*=>\s*\{[\s\S]*?window\.location\.pathname\.startsWith\("\/practice\/writing"\)[\s\S]*?return;[\s\S]*?discardWritingDrafts\(\);/,
    "clearing on a bare unmount would delete the draft on the reload it exists for",
  );
});

test("the mock exam's own autosave is left alone", () => {
  for (const path of [
    ["lib", "exam", "mock.ts"],
    ["components", "exam", "MockWriting.tsx"],
    ["app", "exam", "page.tsx"],
  ]) {
    assert.doesNotMatch(
      src(...path),
      /writing-draft/,
      `${path.join("/")} has its own working persistence and must not be routed through the practice draft`,
    );
  }
});

test("the draft key has one definition, where the sign-out that drops it can see it", () => {
  const storage = src("lib", "progress", "storage.ts");
  assert.match(storage, /export const WRITING_DRAFT_KEY = "bandup\.writing-draft\.v1";/);
  assert.match(storage, /removeLearnerItem\(WRITING_DRAFT_KEY\);/);

  // Spelling it again in the module that writes it is how a rename leaves the
  // sign-out clearing a key nothing writes any more.
  assert.doesNotMatch(src("lib", "writing-draft.ts"), /"bandup\.writing-draft\.v1"/);

  // And it is not synced progress: PROGRESS_KEYS is what account sync uploads,
  // and a crash guard is not a record of anything a learner has done.
  const keys = storage.match(/export const PROGRESS_KEYS = \[([^\]]+)\]/);
  assert.ok(keys, "PROGRESS_KEYS must stay a fixed list");
  assert.doesNotMatch(keys[1], /writing-draft/);
});
