import { spokenForm } from "./speech-text";
import { bundledListeningAudio, bundledListeningAudioUrl, type BundledListeningAudioPart } from "./listening-audio";
import { questionCount, questionWidth, toGroups } from "./questions";
import { LISTENING_TESTS } from "./tests";
import type { ListeningTest } from "./types";

/*
  The spoken frame around a reviewed listening recording: an introduction
  naming the part, reading time before the questions start, a cue to begin, a
  pause partway through Parts 1 to 3, and the line that closes a part. The
  real test speaks all of this; a candidate who has only ever heard BandUp's
  dialogue gets no "you will hear a conversation between..." and no silence
  to read ahead in — straight into the middle of a conversation with no idea
  where they are.

  Nothing here is authored per paper. Every line is generated from what a
  `ListeningTest` already knows — its `context` sentence, its own question
  count and block boundaries, and the sitting-relative question number the
  caller supplies — because the two files that would otherwise carry this
  (lib/types.ts, data/listening-*.json) are being written to by other work at
  the same time and must not gain a frame-specific field just for this.

  ---------------------------------------------------------------------------
  Why this is a second catalogue rather than more entries in the first

  lib/listening-audio.ts is protected by a test
  (tests/server-listening-audio-fallback.test.mjs) that reassembles every
  `parts[].text` for a paper and requires it to equal that paper's dialogue,
  word for word, with nothing added. That is the right rule to protect —
  it is what stops a future change from quietly attaching narration to a
  script a candidate is meant to hear verbatim — and it means a narrator line
  can never be one more entry in that module's `parts` array. So the frame
  lives in its own catalogue, in its own R2 prefix
  (`public/audio/listening-frame/…`), generated by its own route, and the two
  are only ever stitched together at playback time, in
  lib/exam/listening-player.ts.

  ---------------------------------------------------------------------------
  What this deliberately does not add: a worked Example

  Part 1 of the real test plays a worked example before the scored
  questions — a snippet with the answer already given, which is how a
  candidate learns the answer format before anything counts. It cannot be
  built honestly here. The real example is the paper's *own* first exchange
  with its answer spoken aloud, and nothing in a `ListeningTest` says which
  script turn answers which question — the JSON pairs a question with its
  answer, not with a line of dialogue, and there is no field for that pairing
  without editing lib/types.ts, which is off-limits while this ships.
  Treating question one as the example would either hand the candidate its
  real answer before the recording plays it, which breaks the one question it
  touches, or invent an example disconnected from the paper's actual content,
  which is fabricating a demonstration rather than showing one. Neither is
  honest, so this ships the rest of the frame without it.

  ---------------------------------------------------------------------------
  Why an id carries the sitting-relative question number, and why that
  number is checked rather than trusted

  A part's own script never says how many questions the parts before it in
  *this sitting* carried — Part 2 opens on "questions eleven to twenty" only
  because Part 1, whichever paper the sitting drew, asked ten. That number is
  therefore sitting-relative, and the server has no session to consult; the
  only place it can travel is the id itself
  (`listening-6-p3-reading1-21`, say). Accepting any number a request names
  would reopen exactly the door lib/listening-audio.ts was written to keep
  shut — a public endpoint that will speak whatever text a caller can coax
  out of it — so `isReachableStart` below recomputes the one offset a part
  could legitimately open on, from the papers' own uniform question count,
  and refuses every other number rather than trusting it.

  ---------------------------------------------------------------------------
  Why the narrator shares a voice with the speaking examiner

  It has to share with *something*. Deepgram's two Aura models offer exactly
  four voices this app will use as British rather than American, Irish or
  Australian — see the roster note in lib/listening-audio.ts — and all four
  are already spoken for: three are the dialogue cast, and the fourth,
  athena, is already the speaking examiner's voice (lib/examiner-audio.ts).
  There is no fifth British voice to give the listening narrator that is not
  also one of those.

  Reusing athena rather than breaking the app's British-throughout rule for
  this one voice is the better of two imperfect choices, and it costs less
  than it first appears to: the narrator and the dialogue never speak at the
  same moment, so the only real collision is a candidate hearing the same
  voice twice in one sitting — the narrator, and whichever Part 3 paper's
  fourth speaker also drew athena (today, listening-6's Elena and
  listening-14's Malik; every paper with three speakers or fewer never
  reaches athena in the dialogue cast at all). The alternative, an Irish or
  American narrator, is a worse trade: it is audible in every single sitting
  rather than two papers out of thirty-one.
*/
export const LISTENING_FRAME_AUDIO_MODEL = "@cf/deepgram/aura-1";
export const BUNDLED_LISTENING_FRAME_AUDIO_VERSION = "aura-1-v1";
export const BUNDLED_LISTENING_FRAME_AUDIO_VOICE = "athena";

export interface BundledListeningFrameAudio {
  id: string;
  text: string;
  contentVersion: typeof BUNDLED_LISTENING_FRAME_AUDIO_VERSION;
  voice: typeof BUNDLED_LISTENING_FRAME_AUDIO_VOICE;
  contentHash: string;
  cacheKey: string;
}

export interface ListeningAudioStep {
  kind: "audio";
  url: string;
  /** The dialogue turn browser-speech recovery should resume from, should this step fail to play. */
  turnIndex: number;
}

export interface ListeningSilenceStep {
  kind: "silence";
  ms: number;
  /** What the narrator just said, so a caller can show why nothing is playing. */
  label: string;
}

/** One step of a recording's spoken plan, in the order a candidate hears it. */
export type ListeningSequenceStep = ListeningAudioStep | ListeningSilenceStep;

/*
  How long the exam falls silent while the candidate reads ahead.

  The real test gives roughly twenty to thirty seconds at each reading-time
  moment. Twenty-five is the middle of that, used for both the part-opening
  pause and the one partway through Parts 1 to 3, because nothing about a
  generated paper distinguishes how much either moment is worth reading.
*/
/*
  How long the candidate gets to read, and to check.

  The real test does not use one number. It gives about twenty seconds before
  the first block of a conversation, about thirty before the second, and around
  forty-five for Part 4, where all ten questions are read at once because a
  lecture is never interrupted. A flat twenty-five seconds was therefore
  generous in Part 1 and, much worse, mean in Part 4: ten questions in the time
  the real test allows for four or five. That does not make BandUp harder in a
  useful way, it makes it harder than the thing it is preparing someone for.

  So the reading time is a rate — a little under five seconds a question —
  held between the shortest and longest the real test is ever observed to give.
  A block of four gets twenty seconds, a block of ten gets forty-five.
*/
function readingTimeMs(questionsInBlock: number): number {
  const seconds = Math.round(Math.min(45, Math.max(20, questionsInBlock * 4.5)));
  return seconds * 1_000;
}

/*
  And half a minute at the end of the part to check, which the real test always
  gives and this frame did not. It is not dead air: it is the last chance to
  fill a gap before the answers stop being markable, and a candidate who has
  never practised with it is meeting it for the first time in the exam.
*/
const CHECK_TIME_MS = 30_000;

const ONES = [
  "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
  "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen",
  "seventeen", "eighteen", "nineteen",
];
const TENS = ["", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety"];

/**
 * A number the way an examiner says it, rather than the way a synthesiser
 * guesses at a digit. A candidate copies an *answer* down as a digit, but a
 * spoken instruction never should be one — see lib/speech-text.ts for the
 * kinds of things a hyphen or a bare number does to a synthesiser's reading,
 * which this sidesteps entirely by never handing one a digit to interpret in
 * the first place. Covers three digits, generously past the low forties a
 * sitting can actually produce, so a future paper with a larger question
 * count fails by printing an odd-sounding number rather than by throwing.
 */
export function numberWord(n: number): string {
  if (n < 0) return `minus ${numberWord(-n)}`;
  if (n < 20) return ONES[n];
  if (n < 100) {
    const tens = Math.floor(n / 10);
    const ones = n % 10;
    return ones === 0 ? TENS[tens] : `${TENS[tens]}-${ONES[ones]}`;
  }
  const hundreds = Math.floor(n / 100);
  const rest = n % 100;
  return rest === 0 ? `${ONES[hundreds]} hundred` : `${ONES[hundreds]} hundred and ${numberWord(rest)}`;
}

/**
 * How many of a part's ten questions sit in "the first half" the recording
 * pauses after — the block boundary closest to the middle, read from the
 * paper's own rubric rather than assumed to be five and five. A shipped
 * Part 1 is typically seven gap-fills then three multiple-choice questions,
 * not an even split, and a generated "questions six to ten" would name a
 * boundary the paper does not actually have.
 */
function midSplit(test: ListeningTest): number {
  const groups = toGroups(test.questions);
  const total = questionCount(test.questions);
  if (groups.length < 2) return Math.ceil(total / 2);
  let cumulative = 0;
  let best = total;
  let bestDistance = Infinity;
  for (let i = 0; i < groups.length - 1; i += 1) {
    cumulative += groups[i].questions.reduce((sum, q) => sum + questionWidth(q), 0);
    const distance = Math.abs(cumulative - total / 2);
    if (distance < bestDistance) {
      bestDistance = distance;
      best = cumulative;
    }
  }
  return best;
}

/**
 * Which dialogue segment the mid-part silence should precede, estimated from
 * how far through the *audio* the question split falls rather than the
 * script. No paper says which turn a given question is answered in — the
 * JSON pairs a question with its answer, not with a script line — so this
 * assumes a roughly constant speaking rate and finds the segment boundary
 * closest to `fraction` of the way through the paper's total spoken
 * characters. It is an estimate, and the closest a generated pause can
 * honestly get without turn-level question tagging that no paper carries.
 */
function splitSegmentIndex(parts: readonly BundledListeningAudioPart[], fraction: number): number {
  const lengths = parts.map((part) => part.text.length);
  const total = lengths.reduce((sum, length) => sum + length, 0);
  if (parts.length < 2 || total === 0) return parts.length;
  const target = total * fraction;
  let cumulative = 0;
  let bestIndex = parts.length;
  let bestDistance = Infinity;
  for (let i = 0; i < parts.length - 1; i += 1) {
    cumulative += lengths[i];
    const distance = Math.abs(cumulative - target);
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = i + 1;
    }
  }
  return bestIndex;
}

interface FrameStructure {
  /** How many of this part's questions the first half claims. */
  mid: number;
  /** Whether a genuine audio boundary exists to pause at. */
  hasPause: boolean;
  /** Index into this paper's dialogue parts where the second half begins; meaningful only when `hasPause`. */
  splitIndex: number;
}

function frameStructure(test: ListeningTest, partNumber: 1 | 2 | 3 | 4): FrameStructure | null {
  const source = bundledListeningAudio(test.id);
  if (!source) return null;
  const total = questionCount(test.questions);
  const mid = midSplit(test);
  const fraction = total > 0 ? mid / total : 0.5;
  const splitIndex = splitSegmentIndex(source.parts, fraction);
  /*
    Part 4 is the one section the real test does not interrupt — a lecture
    plays straight through rather than pausing halfway, unlike the
    conversations and discussions in Parts 1 to 3. The other three still need
    a genuine interior boundary to pause at; a paper with only one playable
    segment (none shipped today) has nowhere honest to put a pause.
  */
  const hasPause = partNumber !== 4 && splitIndex > 0 && splitIndex < source.parts.length;
  return { mid, hasPause, splitIndex };
}

type FrameLineKind = "intro" | "reading1" | "resume1" | "reading2" | "resume2" | "end";
const RANGE_KINDS = new Set<FrameLineKind>(["reading1", "resume1", "reading2", "resume2"]);
const ID_PATTERN =
  /^(listening-\d+)-p([1-4])-(intro|reading1|resume1|reading2|resume2|end)(?:-(\d+))?$/;

interface FrameLineText {
  id: string;
  text: string;
}

/**
 * The words of one frame line, and the id it is cached under. `from` is this
 * part's first sitting-relative question number; every range-bearing kind
 * needs it and every other kind ignores it, which is exactly the split
 * `RANGE_KINDS` above records and `bundledListeningFrameAudio` checks a
 * request's id against.
 */
function buildLineText(
  test: ListeningTest,
  partNumber: 1 | 2 | 3 | 4,
  kind: FrameLineKind,
  structure: FrameStructure,
  from: number | undefined,
): FrameLineText | null {
  const id = `${test.id}-p${partNumber}-${kind}${from !== undefined ? `-${from}` : ""}`;
  if (kind === "intro") {
    return { id, text: `Part ${numberWord(partNumber)}. ${test.context.trim()}` };
  }
  if (kind === "end") {
    return {
      id,
      /*
        The check line belongs to the end line rather than to a kind of its
        own. It is one breath in the real test — "That is the end of part
        three. You now have half a minute to check your answers." — and
        splitting it in two would buy a second cached object, a second request
        and a second chance to fail, to say the same sentence with a seam in it.
      */
      text:
        partNumber === 4
          ? "That is the end of part four, and the end of the Listening test. You now have half a minute to check your answers."
          : `That is the end of part ${numberWord(partNumber)}. You now have half a minute to check your answers.`,
    };
  }
  if (from === undefined) return null;
  const total = questionCount(test.questions);
  const firstTo = structure.hasPause ? from + structure.mid - 1 : from + total - 1;
  const secondFrom = from + structure.mid;
  const secondTo = from + total - 1;
  switch (kind) {
    case "reading1":
      return {
        id,
        text: structure.hasPause
          ? `First, you have some time to look at questions ${numberWord(from)} to ${numberWord(firstTo)}.`
          : `You have some time to look at questions ${numberWord(from)} to ${numberWord(firstTo)}.`,
      };
    case "resume1":
      /*
        Part 1 carries the warning, and only Part 1 — which is where the real
        test puts it, once, at the start of the paper. It matters more than it
        reads: a candidate practising with a replay button has no reason to
        believe it, and the sentence is the exam telling them plainly that the
        habit they have built will not be available.
      */
      return {
        id,
        text:
          partNumber === 1
            ? `Now listen carefully and answer questions ${numberWord(from)} to ${numberWord(firstTo)}. You should answer the questions as you listen, because you will not hear the recording a second time.`
            : `Now listen carefully and answer questions ${numberWord(from)} to ${numberWord(firstTo)}.`,
      };
    case "reading2":
      if (!structure.hasPause) return null;
      return {
        id,
        text: `Before you hear the rest, you have some time to look at questions ${numberWord(secondFrom)} to ${numberWord(secondTo)}.`,
      };
    case "resume2":
      if (!structure.hasPause) return null;
      return {
        id,
        text: `Now listen carefully and answer questions ${numberWord(secondFrom)} to ${numberWord(secondTo)}.`,
      };
    default:
      return null;
  }
}

function stableContentHash(text: string): string {
  // FNV-1a, not a security primitive — see the identical note in
  // lib/listening-audio.ts. It only changes the R2 key when reviewed wording
  // changes, so an old recording can never be served for new words.
  let hash = 0x811c9dc5;
  for (let index = 0; index < text.length; index += 1) {
    hash ^= text.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function toFrameAudio(line: FrameLineText): BundledListeningFrameAudio {
  // Run through the same normaliser the dialogue endpoint uses, and for the
  // same reason: a context sentence is reviewed prose, not written with a
  // synthesiser's ear, and spokenForm is a no-op on anything that already
  // reads correctly. Hashing the spoken form rather than the raw text means
  // an improvement to those rules retires a cached line exactly as it does
  // for dialogue.
  const text = spokenForm(line.text);
  const contentHash = stableContentHash(text);
  return {
    id: line.id,
    text,
    contentVersion: BUNDLED_LISTENING_FRAME_AUDIO_VERSION,
    voice: BUNDLED_LISTENING_FRAME_AUDIO_VOICE,
    contentHash,
    cacheKey: `public/audio/listening-frame/${BUNDLED_LISTENING_FRAME_AUDIO_VERSION}/${line.id}-${contentHash}.mp3`,
  };
}

function frameLine(
  test: ListeningTest,
  partNumber: 1 | 2 | 3 | 4,
  kind: FrameLineKind,
  structure: FrameStructure,
  from: number | undefined,
  turnIndex: number,
): { step: ListeningAudioStep; text: string } | null {
  const built = buildLineText(test, partNumber, kind, structure, from);
  if (!built) return null;
  const audio = toFrameAudio(built);
  return { step: { kind: "audio", url: bundledListeningFrameAudioUrl(audio.id), turnIndex }, text: audio.text };
}

/*
  Whether every listening paper claims the same number of questions — which
  the content validator enforces (`checkQuestions(..., 10)` in
  scripts/validate-content.mjs) rather than this file, so it is re-derived
  here instead of copied and cannot go stale silently if that number ever
  changes. `null` when papers disagree, which withdraws every range-bearing
  frame line rather than guess at a sitting-relative offset the papers
  cannot themselves justify.
*/
const UNIFORM_QUESTIONS_PER_PART: number | null = (() => {
  const counts = new Set(LISTENING_TESTS.map((test) => questionCount(test.questions)));
  return counts.size === 1 ? [...counts][0] : null;
})();

/**
 * Whether `from` is the one sitting-relative question number a part could
 * legitimately open on. See the module note above for why this is checked
 * rather than trusted.
 */
function isReachableStart(partNumber: 1 | 2 | 3 | 4, from: number): boolean {
  if (UNIFORM_QUESTIONS_PER_PART === null) return false;
  return from === (partNumber - 1) * UNIFORM_QUESTIONS_PER_PART + 1;
}

/**
 * Resolve one frame line from its id alone — no session, no caller-supplied
 * text, just the same deterministic construction `listeningSequence` used to
 * build the id in the first place. The public route calls only this.
 */
export function bundledListeningFrameAudio(id: string | null): BundledListeningFrameAudio | null {
  if (!id) return null;
  const match = ID_PATTERN.exec(id);
  if (!match) return null;
  const [, testId, partRaw, kindRaw, fromRaw] = match;
  const partNumber = Number(partRaw) as 1 | 2 | 3 | 4;
  const kind = kindRaw as FrameLineKind;
  const test = LISTENING_TESTS.find((candidate) => candidate.id === testId);
  if (!test) return null;
  const needsRange = RANGE_KINDS.has(kind);
  if (needsRange === (fromRaw === undefined)) return null;
  const from = fromRaw === undefined ? undefined : Number(fromRaw);
  if (from !== undefined && !isReachableStart(partNumber, from)) return null;
  const structure = frameStructure(test, partNumber);
  if (!structure) return null;
  const line = buildLineText(test, partNumber, kind, structure, from);
  // Belt over the parsing above: a reconstructed line whose own id would not
  // match the one requested is refused rather than served under someone
  // else's key.
  if (!line || line.id !== id) return null;
  return toFrameAudio(line);
}

/** Same-origin on web; `apiUrl()` supplies the deployed API origin on mobile. */
export function bundledListeningFrameAudioUrl(id: string): string {
  const source = bundledListeningFrameAudio(id);
  const query = new URLSearchParams({ id });
  if (source) {
    query.set("v", source.contentVersion);
    query.set("voice", source.voice);
    query.set("hash", source.contentHash);
  }
  return `/api/listening-frame-audio?${query.toString()}`;
}

/**
 * The full spoken plan for one recording: narrator lines, the reviewed
 * dialogue, and the silences between them, in the order a candidate hears
 * them. `from` is this part's first sitting-relative question number — the
 * one thing about the numbering a paper cannot know about itself, because it
 * depends on how many questions the parts before it in *this sitting*
 * carried (see the module note above).
 *
 * Returns null when this paper has no server audio, or no `LISTENING_PART`
 * classification the caller can supply a sensible `partNumber` for — the
 * same "no server audio at all" case lib/exam/listening-player.ts already
 * falls back to browser speech for.
 */
export function listeningSequence(
  testId: string,
  partNumber: 1 | 2 | 3 | 4,
  from: number,
): ListeningSequenceStep[] | null {
  const test = LISTENING_TESTS.find((candidate) => candidate.id === testId);
  const source = bundledListeningAudio(testId);
  if (!test || !source) return null;
  // Checked here as well as inside bundledListeningFrameAudio, so a caller
  // passing the wrong offset fails the whole part up front — before a single
  // request goes out — rather than mid-playback, when the reading-time cue's
  // own URL turns out to 404 against the same check.
  if (!isReachableStart(partNumber, from)) return null;
  const structure = frameStructure(test, partNumber);
  if (!structure) return null;

  const intro = frameLine(test, partNumber, "intro", structure, undefined, 0);
  const reading1 = frameLine(test, partNumber, "reading1", structure, from, 0);
  const resume1 = frameLine(test, partNumber, "resume1", structure, from, 0);
  const end = frameLine(test, partNumber, "end", structure, undefined, test.script.length);
  if (!intro || !reading1 || !resume1 || !end) return null;

  const dialogueStep = (part: BundledListeningAudioPart): ListeningAudioStep => ({
    kind: "audio",
    url: bundledListeningAudioUrl(testId, part.index),
    turnIndex: part.turnIndex,
  });
  const firstChunk = structure.hasPause ? source.parts.slice(0, structure.splitIndex) : source.parts;
  const secondChunk = structure.hasPause ? source.parts.slice(structure.splitIndex) : [];

  const steps: ListeningSequenceStep[] = [
    intro.step,
    reading1.step,
    /* The first block's own size, not a fixed number — a Part 4 opener is all
       ten questions and gets the forty-five seconds the real test gives it. */
    {
      kind: "silence",
      ms: readingTimeMs(structure.hasPause ? structure.mid : questionCount(test.questions)),
      label: reading1.text,
    },
    resume1.step,
    ...firstChunk.map(dialogueStep),
  ];

  if (structure.hasPause) {
    const pauseTurnIndex = secondChunk[0].turnIndex;
    const reading2 = frameLine(test, partNumber, "reading2", structure, from, pauseTurnIndex);
    const resume2 = frameLine(test, partNumber, "resume2", structure, from, pauseTurnIndex);
    // Structurally promised by `hasPause`; a failure here means the id built
    // above could not resolve itself, which toFrameAudio's determinism makes
    // unreachable in practice. Bailing rather than shipping half a pause
    // keeps the failure obvious instead of silently mute.
    if (!reading2 || !resume2) return null;
    steps.push(
      reading2.step,
      { kind: "silence", ms: readingTimeMs(questionCount(test.questions) - structure.mid), label: reading2.text },
      resume2.step,
      ...secondChunk.map(dialogueStep),
    );
  }

  steps.push(end.step);
  /* And the half minute the closing line just promised. A line that says a
     candidate has time to check, followed immediately by silence ending, would
     be the one part of the frame that lies to them. */
  steps.push({ kind: "silence", ms: CHECK_TIME_MS, label: end.text });
  return steps;
}
