/*
  Where the shell points, and what it tells the site when it gets there.

  Generated by `npm run build:miniprogram`, and committed with the production
  value so the project opens and runs straight from a clone. Re-run that
  script with MINIPROGRAM_ORIGIN set to aim the shell at a preview instead —
  the preview Worker is a real deployment on its own URL, so the mini program
  can be tried against a branch before anything reaches bandup.life.
*/
module.exports = {
  /* Origin only — no trailing slash. The page appends the path. */
  SITE_ORIGIN: "https://bandup.life",
  /* Must match MINIPROGRAM_SHELL in lib/platform.ts. */
  SHELL_MARKER: "miniprogram",
};
