/*
  The Worker's entry point: OpenNext's `fetch`, plus the `scheduled` handler it
  does not generate.

  ---------------------------------------------------------------------------
  Why this file has to exist

  `.open-next/worker.js` is generated by `opennextjs-cloudflare build` on every
  build, and its default export has exactly one method: `fetch`. There is no
  configuration hook for adding a `scheduled` handler to it, and editing the
  generated file would last until the next build. OpenNext's own answer, and
  Cloudflare's, is the ordinary Workers one — wrap the generated worker in an
  entry of your own and point `main` at that. Which is all this is: `fetch` is
  handed straight through, and `scheduled` is added beside it.

  `export *` re-exports the Durable Object classes the generated worker
  exports. This project binds none of them today, but a Worker entry that
  silently dropped a class the config referenced would fail at deploy time with
  a message about a missing class rather than about this file.

  The import is of build output that does not exist in a fresh checkout, which
  is why this is `.mjs`: tsconfig.json type-checks every `.ts` file in the
  repository, and a `.ts` entry would fail `next build` on a missing module —
  for a file Next never bundles in the first place.

  ---------------------------------------------------------------------------
  What `scheduled` does, and how you can tell it ran

  It calls the app's own `/api/internal/replica-drain` in process, carrying a
  one-shot ticket that only this handler has ever seen (see
  lib/cloudflare/scheduled-drain-ticket.ts). Everything after that is ordinary
  app code with a normal request context.

  Three ways to see it happened, in increasing order of how much access they
  need: /api/replica/health goes red within thirty minutes if it stops (the
  drain writes a receipt to R2 on every run, and the health check reads it);
  the Cloudflare dashboard lists cron invocations and marks failed ones, which
  is why an unsuccessful drain is rethrown here rather than logged and
  swallowed; and the log line below carries the counts.

  ---------------------------------------------------------------------------
  Previews do not run this

  `.github/workflows/preview-cloudflare.yml` uploads a *version*. Cron triggers
  belong to the deployed Worker, so no schedule fires for a preview — a preview
  can show that this entry still serves requests and that a drain works when it
  is invoked, but only production can show the timer.
*/

import worker from "../.open-next/worker.js";

export * from "../.open-next/worker.js";

const DRAIN_URL = "https://bandup.life/api/internal/replica-drain";
const TICKET_HEADER = "x-bandup-scheduled-drain";

/** Two UUIDs: unguessable, and comfortably over the route's length floor. */
function mintTicket() {
  return `${crypto.randomUUID()}${crypto.randomUUID()}`;
}

function ticketStore() {
  globalThis.__bandupScheduledDrainTickets ??= new Set();
  return globalThis.__bandupScheduledDrainTickets;
}

async function drainReplicaQueues(cron, env, ctx) {
  const ticket = mintTicket();
  ticketStore().add(ticket);
  try {
    const response = await worker.fetch(
      new Request(DRAIN_URL, {
        method: "POST",
        headers: { [TICKET_HEADER]: ticket, "content-type": "application/json" },
        body: "{}",
      }),
      env,
      ctx,
    );
    const summary = await response.json().catch(() => null);
    console.log(JSON.stringify({
      message: "scheduled replica drain",
      cron,
      status: response.status,
      summary,
    }));
    if (!response.ok) {
      /*
        Rethrown, not logged and forgotten. A cron invocation that ends in an
        exception is recorded as a failure by Cloudflare and is visible in the
        dashboard's cron events; one that quietly returns is indistinguishable
        from a healthy run, which is the exact failure mode this whole change
        exists to remove.
      */
      throw new Error(`scheduled replica drain responded ${response.status}`);
    }
  } finally {
    ticketStore().delete(ticket);
  }
}

const bandUpWorker = {
  fetch(request, env, ctx) {
    return worker.fetch(request, env, ctx);
  },
  async scheduled(controller, env, ctx) {
    await drainReplicaQueues(controller?.cron ?? null, env, ctx);
  },
};

export default bandUpWorker;
