import Capacitor
import UIKit

/*
  The bridge half of the native top bar: NativeChromeView is a plain UIKit
  view that knows nothing about Capacitor, and the web app cannot reach a
  view at all — it can only call a plugin method and listen for an event.
  This is what turns one into the other in both directions.

  Registered by hand in MainViewController rather than through
  capacitor.config.json's packageClassList: that list is regenerated by
  `npx cap sync` from installed npm plugin packages, and this plugin is
  neither installed nor published — it is App-target source, the same as
  NativeChromeView itself. registerPluginInstance is the supported route for
  exactly that case.
*/
@objc(NativeChromePlugin)
public class NativeChromePlugin: CAPPlugin, CAPBridgedPlugin {
  public let identifier = "NativeChromePlugin"
  public let jsName = "NativeChrome"
  public let pluginMethods: [CAPPluginMethod] = [
    CAPPluginMethod(name: "enable", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "disable", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "setTheme", returnType: CAPPluginReturnPromise)
  ]

  /// The bar's own content height, independent of whatever the status bar
  /// and notch add. The total the web side gets is always this plus the
  /// current safe area.
  ///
  /// Taken from the view rather than restated here: the view centres its
  /// controls on this same number, so two copies that drifted would put the
  /// controls somewhere other than the middle of the strip they belong to.
  private static var barContentHeight: CGFloat { NativeChromeView.barContentHeight }

  private var chromeView: NativeChromeView?
  private var heightConstraint: NSLayoutConstraint?

  // MARK: - Plugin methods

  @objc func enable(_ call: CAPPluginCall) {
    DispatchQueue.main.async { [weak self] in
      guard let self else {
        call.reject("NativeChromePlugin was deallocated.")
        return
      }
      guard let root = self.bridge?.viewController?.view else {
        call.reject("No root view to attach the native bar to.")
        return
      }

      let view = self.chromeView ?? self.makeChromeView()
      if view.superview == nil {
        root.addSubview(view)
        let constraint = view.heightAnchor.constraint(
          equalToConstant: root.safeAreaInsets.top + NativeChromePlugin.barContentHeight
        )
        self.heightConstraint = constraint
        NSLayoutConstraint.activate([
          // Leading/trailing/top pin to the view itself, not its safe area —
          // the glass has to run under the status bar to shade it the way
          // the rest of the bar shades what is behind that. Only the height
          // is safe-area-aware, because that is the one dimension where
          // "under the status bar" and "the right size" are both true at
          // once.
          view.leadingAnchor.constraint(equalTo: root.leadingAnchor),
          view.trailingAnchor.constraint(equalTo: root.trailingAnchor),
          view.topAnchor.constraint(equalTo: root.topAnchor),
          constraint
        ])
      }

      call.resolve(["height": self.heightConstraint?.constant ?? NativeChromePlugin.barContentHeight])
    }
  }

  @objc func disable(_ call: CAPPluginCall) {
    DispatchQueue.main.async { [weak self] in
      self?.chromeView?.removeFromSuperview()
      self?.chromeView = nil
      self?.heightConstraint = nil
      call.resolve()
    }
  }

  @objc func setTheme(_ call: CAPPluginCall) {
    guard let theme = call.getString("theme") else {
      call.reject("setTheme requires a theme string.")
      return
    }
    DispatchQueue.main.async { [weak self] in
      self?.chromeView?.setTheme(theme)
      call.resolve()
    }
  }

  // MARK: - View

  private func makeChromeView() -> NativeChromeView {
    let view = NativeChromeView(frame: .zero)
    view.translatesAutoresizingMaskIntoConstraints = false
    view.onHome = { [weak self] in self?.notifyListeners("homeTapped", data: nil) }
    view.onMenu = { [weak self] in self?.notifyListeners("menuTapped", data: nil) }
    view.onAccount = { [weak self] in self?.notifyListeners("accountTapped", data: nil) }
    view.onTheme = { [weak self] theme in self?.notifyListeners("themeSelected", data: ["theme": theme]) }
    chromeView = view
    return view
  }

  // MARK: - Safe area

  /*
    Called from MainViewController.viewSafeAreaInsetsDidChange, already on
    the main thread by the time UIKit invokes it — nothing here needs its own
    dispatch. A rotation is the ordinary trigger, but this also covers a
    folding or Stage Manager device resizing the safe area without rotating
    at all, since it reads the inset directly rather than reasoning about
    orientation.
  */
  func updateForSafeAreaChange() {
    guard let constraint = heightConstraint, let root = bridge?.viewController?.view else { return }
    let height = root.safeAreaInsets.top + NativeChromePlugin.barContentHeight
    guard height != constraint.constant else { return }
    constraint.constant = height
    notifyListeners("heightChanged", data: ["height": height])
  }
}
