import Capacitor
import UIKit

/*
  The bridge half of the native top bar: NativeChromeView is a plain UIKit
  view that knows nothing about Capacitor, and the web app cannot reach a
  view at all — it can only call a plugin method and listen for an event.
  This is what turns one into the other in both directions.

  Registered by hand in MainViewController rather than through
  capacitor.config.json's packageClassList: that list is regenerated by
  `npx cap sync` from installed npm plugin packages, and this plugin is
  neither installed nor published — it is App-target source, the same as
  NativeChromeView itself. registerPluginInstance is the supported route for
  exactly that case.
*/
@objc(NativeChromePlugin)
public class NativeChromePlugin: CAPPlugin, CAPBridgedPlugin {
  public let identifier = "NativeChromePlugin"
  public let jsName = "NativeChrome"
  public let pluginMethods: [CAPPluginMethod] = [
    CAPPluginMethod(name: "enable", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "disable", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "setTheme", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "setNavOpen", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "setNavItems", returnType: CAPPluginReturnPromise),
    CAPPluginMethod(name: "setAccount", returnType: CAPPluginReturnPromise)
  ]

  /// The bar's own content height, independent of whatever the status bar
  /// and notch add. The total the web side gets is always this plus the
  /// current safe area.
  ///
  /// Taken from the view rather than restated here: the view centres its
  /// controls on this same number, so two copies that drifted would put the
  /// controls somewhere other than the middle of the strip they belong to.
  private static var barContentHeight: CGFloat { NativeChromeView.barContentHeight }

  private var chromeView: NativeChromeView?
  private var heightConstraint: NSLayoutConstraint?

  /*
    The menu, as the web app last described it.

    Nothing about the sixteen destinations is written down in Swift. lib/nav.ts
    is the single source of truth and it already varies by build — the iOS
    bundle has no /pricing or /billing in it, because Apple requires digital
    content sold inside an app to go through In-App Purchase — and it will keep
    changing. A Swift copy would drift silently and the owner would find out
    from a learner, so the structure is pushed across the bridge and the native
    list renders whatever it is given.
  */
  private var navGroups: [NativeNavListViewController.Group] = []

  /*
    The account button's face, as the web app last described it.

    Held here as well as on the view for the reason navGroups is held here at
    all: the bar can be torn down and built again — disable() drops it, and the
    next enable() makes a fresh one wearing its own defaults — while the web
    app's idea of who is signed in has not changed and so would not be pushed
    again. The theme survives that by being re-synced explicitly after enable()
    resolves; this survives it by the plugin remembering, which is the pattern
    already here and costs the web side nothing.
  */
  private var accountAvatarURL: URL?
  private var accountInitial: String?
  /// The list while it is on screen, so a second tap on the menu button can
  /// close it and a theme change can reach it.
  private weak var navList: NativeNavListViewController?

  // MARK: - Plugin methods

  @objc func enable(_ call: CAPPluginCall) {
    DispatchQueue.main.async { [weak self] in
      guard let self else {
        call.reject("NativeChromePlugin was deallocated.")
        return
      }
      guard let root = self.bridge?.viewController?.view else {
        call.reject("No root view to attach the native bar to.")
        return
      }

      self.attachChrome(over: root)
      call.resolve(["height": self.heightConstraint?.constant ?? NativeChromePlugin.barContentHeight])
    }
  }

  @objc func disable(_ call: CAPPluginCall) {
    DispatchQueue.main.async { [weak self] in
      self?.navList?.dismiss(animated: false)
      self?.chromeView?.removeFromSuperview()
      self?.chromeView = nil
      self?.heightConstraint = nil
      call.resolve()
    }
  }

  @objc func setTheme(_ call: CAPPluginCall) {
    guard let theme = call.getString("theme") else {
      call.reject("setTheme requires a theme string.")
      return
    }
    DispatchQueue.main.async { [weak self] in
      self?.chromeView?.setTheme(theme)
      /* The list is presented over the bar rather than instead of it, and the
         theme control stays reachable while it is open — so a theme chosen
         with the menu up has to reach both surfaces or they disagree in front
         of the person who just changed it. */
      self?.navList?.applyTheme(theme)
      self?.paintPageSubstrate(theme)
      call.resolve()
    }
  }

  /*
    The colour under the web page, which is not the web page's own.

    A WKWebView is given a background colour of its own, and Capacitor sets it
    from `ios.backgroundColor` in capacitor.config.ts — #fbf7f2, chosen so the
    launch does not flash white before the first paint arrives. That is one
    fixed colour, and BandUp has three themes, so in Warm it is invisible and
    in Dark it is a cream sheet lying behind everything the page draws.

    It only ever shows where the page is not drawing, and it turns out there is
    more than one such moment. The one that can be caught here is the navigation
    list opening: with the configured colour swapped for magenta and the screen
    grabbed eight times a second, the web view stops compositing its own layers
    for something over half a second while the zoom runs, and for those frames
    its background colour is the whole screen. The other was reported from a
    real iPhone after a hard scroll back to the top, where the strip beside the
    status bar — the strip `contentInset: "always"` uncovers by insetting the
    scrolled content — came back cream instead of paper. That one would not
    reproduce on the simulator, but the colour in the photograph is #fbf7f2 to
    within the accuracy of a screenshot, so it is this sheet and not another.

    The bar is glass and shades whatever is behind it, which is why the same
    cream reads two different ways: as a pale grey band above a dark bar when
    only the strip is uncovered, and as the whole screen turning cream with the
    bar's edge torn along it when the presentation uncovers everything.

    So the fix is not to stop the colour showing — nothing can promise that —
    but to make it the right colour when it does. Painted from the theme rather
    than configured once, it is the same paper the page paints, and an exposure
    of it is no longer visible at all.

    Both the view and its scroll view, because Capacitor sets both and either
    one left cream would still be the sheet. The window and the root view are
    deliberately not touched: they are behind an opaque web view and were never
    what showed — the appearance the device is in never came into it.
  */
  private func paintPageSubstrate(_ theme: String) {
    let paper = NativeChromeView.colors(for: theme).paper
    bridge?.webView?.backgroundColor = paper
    bridge?.webView?.scrollView.backgroundColor = paper
  }

  /*
    Whether the navigation sheet is open, which only the web app knows.

    The bar raises menuTapped and the web app decides what to do with it, so
    the open state is never the native side's to infer — and the sheet can
    close by Escape, by its own close button, by a tap outside or by a link
    being followed, none of which the bar hears about. This is the way back.

    Defaulting to false rather than rejecting on a missing flag: a call that
    forgot to say should close the sheet's effect, not leave the bar stuck in
    whichever material it happened to be wearing.
  */
  @objc func setNavOpen(_ call: CAPPluginCall) {
    let open = call.getBool("open") ?? false
    DispatchQueue.main.async { [weak self] in
      self?.chromeView?.setNavOpen(open)
      call.resolve()
    }
  }

  /*
    The menu's structure, pushed from the web app.

    Read defensively rather than rejected on a shape mismatch: this is the one
    plugin method whose payload is a nested structure, so there is more to get
    wrong, and a menu missing a row is a smaller failure than a rejected
    promise the web app has no way to recover from. Anything unrecognised is
    dropped and the rest still renders.
  */
  @objc func setNavItems(_ call: CAPPluginCall) {
    let raw = call.getArray("groups", JSObject.self) ?? []
    let groups: [NativeNavListViewController.Group] = raw.compactMap { entry in
      guard let title = entry["title"] as? String else { return nil }
      let items = (entry["items"] as? JSArray ?? []).compactMap { row -> NativeNavListViewController.Item? in
        guard
          let row = row as? JSObject,
          let href = row["href"] as? String,
          let label = row["label"] as? String
        else { return nil }
        return NativeNavListViewController.Item(
          href: href,
          label: label,
          icon: row["icon"] as? String,
          isCurrent: row["current"] as? Bool ?? false
        )
      }
      guard !items.isEmpty else { return nil }
      return NativeNavListViewController.Group(title: title, items: items)
    }

    DispatchQueue.main.async { [weak self] in
      self?.navGroups = groups
      call.resolve()
    }
  }

  /*
    Who is signed in, so the account button can show their face.

    The website's control has three states — a photograph, an initial, the
    generic glyph — and until this existed the app had only the third of them,
    because nothing about a session or a profile is knowable from Swift. This
    is the whole route: the web app already renders those three states in
    SiteHeader.tsx, and it pushes the same two values it decides them from
    rather than the decision itself, so the native side draws them the way
    every other native control here is drawn.

    Both fields are optional and neither is required, in the same spirit as
    setNavOpen's defaulted flag: an account is a thing that goes away, and a
    call that omits a field is asking for the state without it. Nil and nil is
    signed out, which is a legitimate thing to say and must not be a rejection.

    The scheme is checked rather than the URL merely parsed. This value ends up
    in a URLSession request, and the one guarantee worth making about a string
    that arrived from a web layer is that it addresses a web server — not a
    file on the device, not a custom scheme some other app on the phone has
    claimed. Anything else is dropped and the button falls back to the initial,
    which is what a missing photo does anyway.
  */
  @objc func setAccount(_ call: CAPPluginCall) {
    let url = call.getString("avatarUrl")
      .flatMap { URL(string: $0) }
      .flatMap { ["http", "https"].contains($0.scheme?.lowercased() ?? "") ? $0 : nil }
    let initial = call.getString("initial")

    DispatchQueue.main.async { [weak self] in
      guard let self else {
        call.resolve()
        return
      }
      self.accountAvatarURL = url
      self.accountInitial = initial
      self.chromeView?.setAccount(avatarURL: url, initial: initial)
      call.resolve()
    }
  }

  // MARK: - View

  /*
    Where the bar lives, and it is the window rather than the view controller's
    view. That is not tidiness; it is the whole of a defect.

    A modally presented view controller's view goes into a container UIKit adds
    to the window, and for the length of a transition that container is drawn
    across the whole screen — so a bar parented to the root view controller's
    view is painted over by the very list it opened. Recorded on the simulator
    and stepped frame by frame, the bar was completely absent for 590ms of the
    zoom and partly covered for 890ms: the menu glyph went first, then the
    account button, then the theme control one stop at a time as the growing
    card swept leftwards, and last the wordmark and the logo. It returned only
    once the card had settled into its resting frame, whose top strip is
    transparent — which is why the bar looks right in a still and wrong in
    motion, and why the touch forwarding in NativeNavListViewController was
    never evidence either way. Dismissing cost the same again.

    A window subview is outside that container's ancestry, so nothing about a
    presentation can cover it — provided it stays in front of the containers
    added after it, which is what the bringSubviewToFront in toggleNavList is
    for. Deliberately only around our own list, rather than a second UIWindow
    at a raised level that would sit over everything: an alert, a share sheet
    and a photo picker are all things that should be over the bar, and a raised
    window would put the bar over them.

    The height still comes from the view controller's view rather than from the
    window. viewSafeAreaInsetsDidChange on MainViewController is the signal that
    the safe area moved, and that is the view it speaks for; the two carry the
    same insets, since the root view fills the window, so this reads the source
    that is already wired up rather than adding a second one.

    Falling back to the root view when there is no window yet keeps the old
    arrangement, defect and all, for a call that arrives before the scene is on
    screen — a bar in the wrong parent beats no bar. toggleNavList re-homes it
    before it can matter.
  */
  private func attachChrome(over root: UIView) {
    let view = chromeView ?? makeChromeView()
    let host: UIView = root.window ?? root
    guard view.superview !== host else { return }

    /* Held by the view itself rather than by a superview, so unlike the other
       three it survives removeFromSuperview and has to be let go by hand. */
    heightConstraint?.isActive = false
    view.removeFromSuperview()
    host.addSubview(view)

    let constraint = view.heightAnchor.constraint(
      equalToConstant: root.safeAreaInsets.top + NativeChromePlugin.barContentHeight
    )
    heightConstraint = constraint
    NSLayoutConstraint.activate([
      // Leading/trailing/top pin to the host itself, not its safe area —
      // the glass has to run under the status bar to shade it the way
      // the rest of the bar shades what is behind that. Only the height
      // is safe-area-aware, because that is the one dimension where
      // "under the status bar" and "the right size" are both true at
      // once.
      view.leadingAnchor.constraint(equalTo: host.leadingAnchor),
      view.trailingAnchor.constraint(equalTo: host.trailingAnchor),
      view.topAnchor.constraint(equalTo: host.topAnchor),
      constraint
    ])
  }

  private func makeChromeView() -> NativeChromeView {
    let view = NativeChromeView(frame: .zero)
    view.translatesAutoresizingMaskIntoConstraints = false
    view.onHome = { [weak self] in
      /* The bar stays live above the open list, so home can be tapped with
         the menu up — and a route change under a standing menu leaves the
         sheet stranded over a page it did not open on. Closing first is what
         the website does from inside its own sheet. */
      self?.navList?.dismiss(animated: true)
      self?.notifyListeners("homeTapped", data: nil)
    }
    view.onMenu = { [weak self] in self?.toggleNavList() }
    view.onAccount = { [weak self] in
      self?.navList?.dismiss(animated: true)
      self?.notifyListeners("accountTapped", data: nil)
    }
    view.onTheme = { [weak self] theme in
      self?.navList?.applyTheme(theme)
      /* Painted here as well as in setTheme(_:), for the same reason the list
         above is: a theme chosen on the bar reaches the web app, which sets it
         and syncs it back, and the trip out to JavaScript and in again is long
         enough for a menu opened straight after the tap to still be sampling
         the old paper. The echo that follows finds this already done. */
      self?.paintPageSubstrate(theme)
      self?.notifyListeners("themeSelected", data: ["theme": theme])
    }
    /* A fresh bar starts on the generic glyph, so whoever is signed in has to
       be told to it again — see the stored pair above for why this side is the
       one that remembers. Harmless before anyone signs in, when both are nil
       and this says exactly what the view already assumed. */
    view.setAccount(avatarURL: accountAvatarURL, initial: accountInitial)
    chromeView = view
    return view
  }

  // MARK: - The navigation list

  /*
    Where the menu button's tap is answered, and it is here rather than on the
    web side on purpose.

    It used to travel: the bar raised menuTapped, the web app toggled a piece
    of React state, and a DOM sheet grew out of the middle of the screen
    because the button it should have grown from is not in the DOM at all. The
    whole point of this change is that the list comes out of the button, and
    Apple's zoom transition takes the source view directly — so the tap has to
    be answered somewhere that can see both a UIView and a UIViewController.

    NativeChromeView cannot: it is a plain view that deliberately knows nothing
    about Capacitor or about view controllers, which is what lets it be built
    and reasoned about on its own. The plugin can, because it already holds the
    bridge and the bridge holds the presenting view controller. Answering it
    here also means the transition begins in the same run loop turn as the
    touch, rather than after a round trip out to JavaScript and back — a zoom
    that starts a frame or two late does not read as the button opening.

    The web app is still told, because it still owns the state: `menuTapped` on
    the way up so its own `openPath` agrees, and navDismissed or
    navItemSelected on the way down.
  */
  private func toggleNavList() {
    if let open = navList {
      open.dismiss(animated: true)
      return
    }
    guard
      let presenter = bridge?.viewController,
      !navGroups.isEmpty
    else {
      /* Nothing to show — the web app has not described the menu yet, which
         in practice only happens if setNavItems has not landed. Silently
         doing nothing beats presenting an empty sheet, and beats telling the
         web app a menu is open when none is. */
      return
    }

    /* Re-homed here as well as in enable(), for the one case enable() cannot
       cover: a call that arrived before the scene had a window left the bar
       parented to the view controller's view. There is certainly a window by
       the time a menu button has been tapped, and everything below depends on
       the bar being outside the presentation's container. */
    attachChrome(over: presenter.view)

    let list = NativeNavListViewController(
      groups: navGroups,
      theme: chromeView?.selectedTheme ?? "warm",
      topInset: heightConstraint?.constant ?? NativeChromePlugin.barContentHeight,
      /* The bar keeps its own touches while the list is over the page — the
         theme control and the account button stay live up there, the same way
         the website's header does above its own sheet. */
      passthroughTarget: chromeView
    )
    /*
      Over, not instead of. The bar stays on screen above the list exactly as
      the website's header stays above its own sheet, which is what keeps the
      menu button visible for the zoom to unwind into, keeps a second tap on it
      able to close the list, and keeps the bar's clear-glass open state worth
      having at all. `.fullScreen` would tear the presenting view out from
      under it after the transition.
    */
    list.modalPresentationStyle = .overFullScreen

    if #available(iOS 18.0, *) {
      /*
        The whole change, in one property. The list grows out of the menu
        button and unwinds back into it, and the swipe-to-dismiss that comes
        with it is Apple's rather than ours.

        The provider is called more than once over a transition's life — on the
        way out as well as the way in — so it resolves the button through the
        bar each time rather than capturing it, and yields nil if the bar has
        been torn down in between. A nil source is a supported answer: the
        transition falls back to a plain one rather than failing.

        There is a sourceBarButtonItemProvider overload on 26 that is not the
        one to reach for here — the menu button is a plain UIButton on a view
        we draw, not an item in a navigation bar.
      */
      list.preferredTransition = .zoom { [weak self] _ in
        self?.chromeView?.menuSourceView
      }
    } else {
      /* No zoom before 18, so the list still opens — plainly. A menu that
         does not appear at all is a broken app; a menu that appears without
         growing out of the button is last year's menu. */
      list.modalTransitionStyle = .crossDissolve
    }

    /*
      And the bar back on top of it.

      UIKit adds the presentation's container view to the window as the last
      subview, above the bar however early the bar got there — so the ordering
      is something to restate once per presentation rather than to establish
      once. It cannot be restated beside present(), because present() does not
      build the presentation while you wait: logged on the simulator, the
      window still held only the root view and the bar when present() returned,
      and gained the container a run loop turn later. viewWillAppear on the list
      is the first moment the container is really there, and it is still ahead
      of the transition's first frame, so nothing is drawn in the wrong order.

      Only for our own list, deliberately, and never as a raised UIWindow that
      would sit over everything: an alert, a share sheet and a photo picker all
      belong over the bar, and each of those arrives as its own container above
      the bar exactly as it should.
    */
    list.onWillAppear = { [weak self] in
      guard let view = self?.chromeView, let window = view.window else { return }
      window.bringSubviewToFront(view)
    }

    list.onSelect = { [weak self] href in
      self?.navList = nil
      self?.notifyListeners("navItemSelected", data: ["href": href])
    }
    list.onDismissed = { [weak self] in
      self?.navList = nil
      self?.notifyListeners("navDismissed", data: nil)
    }

    navList = list
    notifyListeners("menuTapped", data: nil)
    presenter.present(list, animated: true)
  }

  // MARK: - Safe area

  /*
    Called from MainViewController.viewSafeAreaInsetsDidChange, already on
    the main thread by the time UIKit invokes it — nothing here needs its own
    dispatch. A rotation is the ordinary trigger, but this also covers a
    folding or Stage Manager device resizing the safe area without rotating
    at all, since it reads the inset directly rather than reasoning about
    orientation.
  */
  func updateForSafeAreaChange() {
    guard let constraint = heightConstraint, let root = bridge?.viewController?.view else { return }
    let height = root.safeAreaInsets.top + NativeChromePlugin.barContentHeight
    guard height != constraint.constant else { return }
    constraint.constant = height
    notifyListeners("heightChanged", data: ["height": height])
  }
}
